---
spring:
  application:
    name: PAYMENT-HISTORY-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${vcap.application.port:9000}
logging:
  level:
    io.pivotal.mastercard: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      